const listfile = [
    ["0", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "aircon_3ph1", "monitor", "energy_r"],
    ["1", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "aircon_3ph1", "monitor", "energy_s"],
    ["2", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "aircon_3ph1", "monitor", "energy_t"],
    ["3", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "light1", "monitor", "energy"],
    ["4", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "outlet1", "monitor", "energy"],
    ["5", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor1", "monitor", "humidity"],
    ["6", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor1", "monitor", "illuminance"],
    ["7", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor1", "monitor", "pir"],
    ["8", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor1", "monitor", "temperature"],
    ["9", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor2", "monitor", "humidity"],
    ["10", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor2", "monitor", "illuminance"],
    ["11", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor2", "monitor", "pir"],
    ["12", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor2", "monitor", "temperature"],
    ["13", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor3", "monitor", "humidity"],
    ["14", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor3", "monitor", "illuminance"],
    ["15", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor3", "monitor", "pir"],
    ["16", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor3", "monitor", "temperature"],
    ["17", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor4", "monitor", "humidity"],
    ["18", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor4", "monitor", "illuminance"],
    ["19", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor4", "monitor", "pir"],
    ["20", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z1", "sensor4", "monitor", "temperature"],
    ["21", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "aircon1", "monitor", "energy"],
    ["22", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "light1", "monitor", "energy"],
    ["23", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "light2", "monitor", "energy"],
    ["24", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "outlet1", "monitor", "energy"],
    ["25", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor1", "monitor", "humidity"],
    ["26", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor1", "monitor", "illuminance"],
    ["27", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor1", "monitor", "pir"],
    ["28", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor1", "monitor", "temperature"],
    ["29", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor2", "monitor", "humidity"],
    ["30", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor2", "monitor", "illuminance"],
    ["31", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor2", "monitor", "pir"],
    ["32", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor2", "monitor", "temperature"],
    ["33", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor3", "monitor", "humidity"],
    ["34", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor3", "monitor", "illuminance"],
    ["35", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor3", "monitor", "pir"],
    ["36", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z2", "sensor3", "monitor", "temperature"],
    ["37", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "aircon_3ph1", "monitor", "energy_r"],
    ["38", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "aircon_3ph1", "monitor", "energy_s"],
    ["39", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "aircon_3ph1", "monitor", "energy_t"],
    ["40", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "outlet1", "monitor", "energy"],
    ["41", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor1", "monitor", "humidity"],
    ["42", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor1", "monitor", "illuminance"],
    ["43", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor1", "monitor", "pir"],
    ["44", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor1", "monitor", "temperature"],
    ["45", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor2", "monitor", "humidity"],
    ["46", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor2", "monitor", "illuminance"],
    ["47", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor2", "monitor", "pir"],
    ["48", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z3", "sensor2", "monitor", "temperature"],
    ["49", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "aircon_3ph1", "monitor", "energy_r"],
    ["50", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "aircon_3ph1", "monitor", "energy_s"],
    ["51", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "aircon_3ph1", "monitor", "energy_t"],
    ["52", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "light1", "monitor", "energy"],
    ["53", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "outlet1", "monitor", "energy"],
    ["54", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor1", "monitor", "humidity"],
    ["55", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor1", "monitor", "illuminance"],
    ["56", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor1", "monitor", "pir"],
    ["57", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor1", "monitor", "temperature"],
    ["58", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor2", "monitor", "humidity"],
    ["59", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor2", "monitor", "illuminance"],
    ["60", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor2", "monitor", "pir"],
    ["61", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z4", "sensor2", "monitor", "temperature"],
    ["62", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "aircon_3ph1", "monitor", "energy_r"],
    ["63", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "aircon_3ph1", "monitor", "energy_s"],
    ["64", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "aircon_3ph1", "monitor", "energy_t"],
    ["65", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "light1", "monitor", "energy"],
    ["66", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor1", "monitor", "humidity"],
    ["67", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor1", "monitor", "illuminance"],
    ["68", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor1", "monitor", "pir"],
    ["69", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor1", "monitor", "temperature"],
    ["70", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor2", "monitor", "humidity"],
    ["71", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor2", "monitor", "illuminance"],
    ["72", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor2", "monitor", "pir"],
    ["73", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z5", "sensor2", "monitor", "temperature"],
    ["74", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "aircon_3ph1", "monitor", "energy_r"],
    ["75", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "aircon_3ph1", "monitor", "energy_s"],
    ["76", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "aircon_3ph1", "monitor", "energy_t"],
    ["77", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "light1", "monitor", "energy"],
    ["78", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "outlet1", "monitor", "energy"],
    ["79", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor1", "monitor", "humidity"],
    ["80", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor1", "monitor", "illuminance"],
    ["81", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor1", "monitor", "pir"],
    ["82", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor1", "monitor", "temperature"],
    ["83", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor2", "monitor", "humidity"],
    ["84", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor2", "monitor", "illuminance"],
    ["85", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor2", "monitor", "pir"],
    ["86", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z6", "sensor2", "monitor", "temperature"],
    ["87", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "aircon_3ph1", "monitor", "energy_r"],
    ["88", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "aircon_3ph1", "monitor", "energy_s"],
    ["89", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "aircon_3ph1", "monitor", "energy_t"],
    ["90", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "light1", "monitor", "energy"],
    ["91", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "light2", "monitor", "energy"],
    ["92", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "outlet1", "monitor", "energy"],
    ["93", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "outlet2", "monitor", "energy"],
    ["94", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor1", "monitor", "humidity"],
    ["95", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor1", "monitor", "illuminance"],
    ["96", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor1", "monitor", "pir"],
    ["97", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor1", "monitor", "temperature"],
    ["98", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor2", "monitor", "humidity"],
    ["99", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor2", "monitor", "illuminance"],
    ["100", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor2", "monitor", "pir"],
    ["101", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor2", "monitor", "temperature"],
    ["102", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor3", "monitor", "humidity"],
    ["103", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor3", "monitor", "illuminance"],
    ["104", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor3", "monitor", "pir"],
    ["105", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor3", "monitor", "temperature"],
    ["106", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor4", "monitor", "humidity"],
    ["107", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor4", "monitor", "illuminance"],
    ["108", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor4", "monitor", "pir"],
    ["109", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z7", "sensor4", "monitor", "temperature"],
    ["110", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "aircon_3ph1", "monitor", "energy_r"],
    ["111", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "aircon_3ph1", "monitor", "energy_s"],
    ["112", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "aircon_3ph1", "monitor", "energy_t"],
    ["113", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "light1", "monitor", "energy"],
    ["114", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "outlet1", "monitor", "energy"],
    ["115", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor1", "monitor", "humidity"],
    ["116", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor1", "monitor", "illuminance"],
    ["117", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor1", "monitor", "pir"],
    ["118", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor1", "monitor", "temperature"],
    ["119", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor2", "monitor", "humidity"],
    ["120", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor2", "monitor", "illuminance"],
    ["121", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor2", "monitor", "pir"],
    ["122", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor2", "monitor", "temperature"],
    ["123", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor3", "monitor", "humidity"],
    ["124", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor3", "monitor", "illuminance"],
    ["125", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor3", "monitor", "pir"],
    ["126", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor3", "monitor", "temperature"],
    ["127", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor4", "monitor", "humidity"],
    ["128", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor4", "monitor", "illuminance"],
    ["129", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor4", "monitor", "pir"],
    ["130", "eng4", "fl13", "north", "lab_tsrl_dsprl_emrl", "z8", "sensor4", "monitor", "temperature"],
    ["131", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor1", "monitor", "humidity"],
    ["132", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor1", "monitor", "illuminance"],
    ["133", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor1", "monitor", "pir"],
    ["134", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor1", "monitor", "temperature"],
    ["135", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor2", "monitor", "humidity"],
    ["136", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor2", "monitor", "illuminance"],
    ["137", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor2", "monitor", "pir"],
    ["138", "eng4", "fl13", "corridor", "elevetorfront", "z1", "sensor2", "monitor", "temperature"],
    ["139", "eng4", "fl13", "corridor", "walkingpath", "z1", "outlet1", "monitor", "energy"],
    ["140", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor1", "monitor", "humidity"],
    ["141", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor1", "monitor", "illuminance"],
    ["142", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor1", "monitor", "pir"],
    ["143", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor1", "monitor", "temperature"],
    ["144", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor2", "monitor", "humidity"],
    ["145", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor2", "monitor", "illuminance"],
    ["146", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor2", "monitor", "pir"],
    ["147", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor2", "monitor", "temperature"],
    ["148", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor3", "monitor", "humidity"],
    ["149", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor3", "monitor", "illuminance"],
    ["150", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor3", "monitor", "pir"],
    ["151", "eng4", "fl13", "corridor", "walkingpath", "z1", "sensor3", "monitor", "temperature"],
    ["152", "eng4", "fl13", "north", "ambient", "z1", "sensor1", "monitor", "battery"],
    ["153", "eng4", "fl13", "north", "ambient", "z1", "sensor1", "monitor", "humidity"],
    ["154", "eng4", "fl13", "north", "ambient", "z1", "sensor1", "monitor", "illuminance"],
    ["155", "eng4", "fl13", "north", "ambient", "z1", "sensor1", "monitor", "temperature"],
    ["156", "eng4", "fl13", "north", "ambient", "z2", "sensor1", "monitor", "battery"],
    ["157", "eng4", "fl13", "north", "ambient", "z2", "sensor1", "monitor", "humidity"],
    ["158", "eng4", "fl13", "north", "ambient", "z2", "sensor1", "monitor", "illuminance"],
    ["159", "eng4", "fl13", "north", "ambient", "z2", "sensor1", "monitor", "temperature"],
    ["160", "eng4", "fl13", "north", "lab_cu_ais_rf_rtl", "z1", "aircon1", "monitor", "energy"],
    ["161", "eng4", "fl13", "north", "lab_cu_ais_rf_rtl", "z1", "sensor1", "monitor", "humidity"],
    ["162", "eng4", "fl13", "north", "lab_cu_ais_rf_rtl", "z1", "sensor1", "monitor", "illuminance"],
    ["163", "eng4", "fl13", "north", "lab_cu_ais_rf_rtl", "z1", "sensor1", "monitor", "pir"],
    ["164", "eng4", "fl13", "north", "lab_cu_ais_rf_rtl", "z1", "sensor1", "monitor", "temperature"],
    ["165", "eng4", "fl13", "north", "lab_studio", "z1", "sensor1", "monitor", "humidity"],
    ["166", "eng4", "fl13", "north", "lab_studio", "z1", "sensor1", "monitor", "illuminance"],
    ["167", "eng4", "fl13", "north", "lab_studio", "z1", "sensor1", "monitor", "pir"],
    ["168", "eng4", "fl13", "north", "lab_studio", "z1", "sensor1", "monitor", "temperature"],
    ["169", "eng4", "fl13", "north", "lab_telecommunication", "z1", "aircon1", "monitor", "energy"],
    ["170", "eng4", "fl13", "north", "lab_telecommunication", "z1", "sensor1", "monitor", "humidity"],
    ["171", "eng4", "fl13", "north", "lab_telecommunication", "z1", "sensor1", "monitor", "illuminance"],
    ["172", "eng4", "fl13", "north", "lab_telecommunication", "z1", "sensor1", "monitor", "pir"],
    ["173", "eng4", "fl13", "north", "lab_telecommunication", "z1", "sensor1", "monitor", "temperature"],
    ["174", "eng4", "fl13", "north", "room_pantry", "z1", "aircon1", "monitor", "energy"],
    ["175", "eng4", "fl13", "north", "room_pantry", "z1", "light1", "monitor", "energy"],
    ["176", "eng4", "fl13", "north", "room_pantry", "z1", "sensor1", "monitor", "humidity"],
    ["177", "eng4", "fl13", "north", "room_pantry", "z1", "sensor1", "monitor", "illuminance"],
    ["178", "eng4", "fl13", "north", "room_pantry", "z1", "sensor1", "monitor", "pir"],
    ["179", "eng4", "fl13", "north", "room_pantry", "z1", "sensor1", "monitor", "temperature"],
    ["180", "eng4", "fl13", "north", "room_server", "z1", "aircon1", "monitor", "energy"],
    ["181", "eng4", "fl13", "north", "room_server", "z1", "aircon2", "monitor", "energy"],
    ["182", "eng4", "fl13", "north", "room_server", "z1", "aircon3", "monitor", "energy"],
    ["183", "eng4", "fl13", "north", "room_server", "z1", "outlet1", "monitor", "energy"],
    ["184", "eng4", "fl13", "north", "room_server", "z1", "outlet2", "monitor", "energy"],
    ["185", "eng4", "fl13", "north", "room_server", "z1", "outlet3", "monitor", "energy"],
    ["186", "eng4", "fl13", "north", "room_server", "z1", "outlet4", "monitor", "energy"],
    ["187", "eng4", "fl13", "north", "room_server", "z1", "sensor1", "monitor", "humidity"],
    ["188", "eng4", "fl13", "north", "room_server", "z1", "sensor1", "monitor", "illuminance"],
    ["189", "eng4", "fl13", "north", "room_server", "z1", "sensor1", "monitor", "pir"],
    ["190", "eng4", "fl13", "north", "room_server", "z1", "sensor1", "monitor", "temperature"],
    ["191", "eng4", "fl13", "south", "lectureroom_2", "z1", "aircon_3ph1", "monitor", "energy_r"],
    ["192", "eng4", "fl13", "south", "lectureroom_2", "z1", "aircon_3ph1", "monitor", "energy_s"],
    ["193", "eng4", "fl13", "south", "lectureroom_2", "z1", "aircon_3ph1", "monitor", "energy_t"],
    ["194", "eng4", "fl13", "south", "lectureroom_2", "z1", "light1", "monitor", "energy"],
    ["195", "eng4", "fl13", "south", "lectureroom_2", "z1", "outlet1", "monitor", "energy"],
    ["196", "eng4", "fl13", "south", "lectureroom_2", "z1", "sensor1", "monitor", "humidity"],
    ["197", "eng4", "fl13", "south", "lectureroom_2", "z1", "sensor1", "monitor", "illuminance"],
    ["198", "eng4", "fl13", "south", "lectureroom_2", "z1", "sensor1", "monitor", "pir"],
    ["199", "eng4", "fl13", "south", "lectureroom_2", "z1", "sensor1", "monitor", "temperature"],
    ["200", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "aircon_3ph1", "monitor", "energy_r"],
    ["201", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "aircon_3ph1", "monitor", "energy_s"],
    ["202", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "aircon_3ph1", "monitor", "energy_t"],
    ["203", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "light1", "monitor", "energy"],
    ["204", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "outlet1", "monitor", "energy"],
    ["205", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "outlet2", "monitor", "energy"],
    ["206", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor1", "monitor", "humidity"],
    ["207", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor1", "monitor", "illuminance"],
    ["208", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor1", "monitor", "pir"],
    ["209", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor1", "monitor", "temperature"],
    ["210", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor2", "monitor", "humidity"],
    ["211", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor2", "monitor", "illuminance"],
    ["212", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor2", "monitor", "pir"],
    ["213", "eng4", "fl13", "south", "lectureroom_dsp", "z1", "sensor2", "monitor", "temperature"],
    ["214", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "aircon_3ph1", "monitor", "energy_r"],
    ["215", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "aircon_3ph1", "monitor", "energy_s"],
    ["216", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "aircon_3ph1", "monitor", "energy_t"],
    ["217", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "outlet1", "monitor", "energy"],
    ["218", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor1", "monitor", "humidity"],
    ["219", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor1", "monitor", "illuminance"],
    ["220", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor1", "monitor", "pir"],
    ["221", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor1", "monitor", "temperature"],
    ["222", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor2", "monitor", "humidity"],
    ["223", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor2", "monitor", "illuminance"],
    ["224", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor2", "monitor", "pir"],
    ["225", "eng4", "fl13", "south", "lectureroom_dsp", "z2", "sensor2", "monitor", "temperature"],
    ["226", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "aircon1", "monitor", "energy"],
    ["227", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "light1", "monitor", "energy"],
    ["228", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "light2", "monitor", "energy"],
    ["229", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "outlet1", "monitor", "energy"],
    ["230", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "outlet2", "monitor", "energy"],
    ["231", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor1", "monitor", "humidity"],
    ["232", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor1", "monitor", "illuminance"],
    ["233", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor1", "monitor", "pir"],
    ["234", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor1", "monitor", "temperature"],
    ["235", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor2", "monitor", "humidity"],
    ["236", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor2", "monitor", "illuminance"],
    ["237", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor2", "monitor", "pir"],
    ["238", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor2", "monitor", "temperature"],
    ["239", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor3", "monitor", "humidity"],
    ["240", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor3", "monitor", "illuminance"],
    ["241", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor3", "monitor", "pir"],
    ["242", "eng4", "fl13", "south", "room_cak_cpp_lwk", "z1", "sensor3", "monitor", "temperature"],
    ["243", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "aircon1", "monitor", "energy"],
    ["244", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "light1", "monitor", "energy"],
    ["245", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "light2", "monitor", "energy"],
    ["246", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "outlet1", "monitor", "energy"],
    ["247", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor2", "monitor", "humidity"],
    ["248", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor2", "monitor", "illuminance"],
    ["249", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor2", "monitor", "pir"],
    ["250", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor2", "monitor", "temperature"],
    ["251", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor3", "monitor", "humidity"],
    ["252", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor3", "monitor", "illuminance"],
    ["253", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor3", "monitor", "pir"],
    ["254", "eng4", "fl13", "south", "room_csc_jpl_ccr", "z1", "sensor3", "monitor", "temperature"],
    ["255", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "aircon1", "monitor", "energy"],
    ["256", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "light1", "monitor", "energy"],
    ["257", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "outlet1", "monitor", "energy"],
    ["258", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor1", "monitor", "humidity"],
    ["259", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor1", "monitor", "illuminance"],
    ["260", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor1", "monitor", "pir"],
    ["261", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor1", "monitor", "temperature"],
    ["262", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor2", "monitor", "humidity"],
    ["263", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor2", "monitor", "illuminance"],
    ["264", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor2", "monitor", "pir"],
    ["265", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor2", "monitor", "temperature"],
    ["266", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor3", "monitor", "humidity"],
    ["267", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor3", "monitor", "illuminance"],
    ["268", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor3", "monitor", "pir"],
    ["269", "eng4", "fl13", "south", "room_pkp_pjp_was", "z1", "sensor3", "monitor", "temperature"],
    ["270", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "aircon1", "monitor", "energy"],
    ["271", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "aircon_3ph1", "monitor", "energy_r"],
    ["272", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "aircon_3ph1", "monitor", "energy_s"],
    ["273", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "aircon_3ph1", "monitor", "energy_t"],
    ["274", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "light1", "monitor", "energy"],
    ["275", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "light2", "monitor", "energy"],
    ["276", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "outlet1", "monitor", "energy"],
    ["277", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "outlet2", "monitor", "energy"],
    ["278", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor1", "monitor", "humidity"],
    ["279", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor1", "monitor", "illuminance"],
    ["280", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor1", "monitor", "pir"],
    ["281", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor1", "monitor", "temperature"],
    ["282", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor2", "monitor", "humidity"],
    ["283", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor2", "monitor", "illuminance"],
    ["284", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor2", "monitor", "pir"],
    ["285", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor2", "monitor", "temperature"],
    ["286", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor3", "monitor", "humidity"],
    ["287", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor3", "monitor", "illuminance"],
    ["288", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor3", "monitor", "pir"],
    ["289", "eng4", "fl13", "south", "room_sav_dwc_nts", "z1", "sensor3", "monitor", "temperature"],
    ["290", "eng4", "fl13", "emucb13a", "sub06", "phase_t", "load12", "monitor", "energy"],
    ["291", "eng4", "fl13", "emucb13a", "sub08", "phase_r", "load13", "monitor", "energy"],
    ["292", "eng4", "fl13", "emucb13a", "sub12", "phase_s", "load15", "monitor", "energy"],
    ["293", "eng4", "fl13", "emucb13a", "sub21", "phase_r", "load25", "monitor", "energy"],
    ["294", "eng4", "fl13", "emucb13a", "sub25", "phase_t", "load36", "monitor", "energy"],
    ["295", "eng4", "fl13", "emucb13b", "sub08", "phase_s", "load9", "monitor", "energy"],
    ["296", "eng4", "fl13", "emucb13b", "sub11", "phase_t", "load13", "monitor", "energy"],
    ["297", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor1", "monitor", "humidity"],
    ["298", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor1", "monitor", "illuminance"],
    ["299", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor1", "monitor", "pir"],
    ["300", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor1", "monitor", "temperature"],
    ["301", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor2", "monitor", "humidity"],
    ["302", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor2", "monitor", "illuminance"],
    ["303", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor2", "monitor", "pir"],
    ["304", "eng4", "fl12", "corridor", "elevatorfront", "z1", "sensor2", "monitor", "temperature"],
    ["305", "eng4", "fl12", "corridor", "walkingpath", "z1", "outlet1", "monitor", "energy"],
    ["306", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor1", "monitor", "humidity"],
    ["307", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor1", "monitor", "illuminance"],
    ["308", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor1", "monitor", "pir"],
    ["309", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor1", "monitor", "temperature"],
    ["310", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor2", "monitor", "humidity"],
    ["311", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor2", "monitor", "illuminance"],
    ["312", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor2", "monitor", "pir"],
    ["313", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor2", "monitor", "temperature"],
    ["314", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor3", "monitor", "humidity"],
    ["315", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor3", "monitor", "illuminance"],
    ["316", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor3", "monitor", "pir"],
    ["317", "eng4", "fl12", "corridor", "walkingpath", "z1", "sensor3", "monitor", "temperature"],
    ["318", "eng4", "fl12", "emucb12b", "sub06", "phase_r", "load7", "monitor", "energy"],
    ["319", "eng4", "fl12", "emucb12b", "sub13", "phase_r", "load14", "monitor", "energy"],
    ["320", "eng4", "fl12", "emucb12b", "sub14", "phase_s", "load15", "monitor", "energy"],
    ["321", "eng4", "fl12", "emucb12b", "sub16", "phase_t", "load17", "monitor", "energy"],
    ["322", "eng4", "fl12", "emucb12b", "sub26", "phase_s", "load27", "monitor", "energy"],
    ["323", "eng4", "fl12", "emucb5", "sub07", "phase_r", "load8", "monitor", "energy"],
    ["324", "eng4", "fl12", "emucb5", "sub12", "phase_r", "load13", "monitor", "energy"],
    ["325", "eng4", "fl12", "emucb5", "sub14", "phase_s", "load15", "monitor", "energy"],
    ["326", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "aircon1", "monitor", "energy"],
    ["327", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "light1", "monitor", "energy"],
    ["328", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor1", "monitor", "PIR"],
    ["329", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor1", "monitor", "beeper"],
    ["330", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor1", "monitor", "humidity"],
    ["331", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor1", "monitor", "illuminance"],
    ["332", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor1", "monitor", "temperature"],
    ["333", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor2", "monitor", "PIR"],
    ["334", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor2", "monitor", "beeper"],
    ["335", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor2", "monitor", "humidity"],
    ["336", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor2", "monitor", "illuminance"],
    ["337", "eng4", "fl12", "north", "lectureroom_psrl", "z1", "sensor2", "monitor", "temperature"],
    ["338", "eng4", "fl12", "north", "room_bea", "z1", "aircon1", "monitor", "energy"],
    ["339", "eng4", "fl12", "north", "room_bea", "z1", "sensor1", "monitor", "PIR"],
    ["340", "eng4", "fl12", "north", "room_bea", "z1", "sensor1", "monitor", "beeper"],
    ["341", "eng4", "fl12", "north", "room_bea", "z1", "sensor1", "monitor", "humidity"],
    ["342", "eng4", "fl12", "north", "room_bea", "z1", "sensor1", "monitor", "illuminance"],
    ["343", "eng4", "fl12", "north", "room_bea", "z1", "sensor1", "monitor", "temperature"],
    ["344", "eng4", "fl12", "north", "room_ccc", "z1", "aircon1", "monitor", "energy"],
    ["345", "eng4", "fl12", "north", "room_ccc", "z1", "light1", "monitor", "energy"],
    ["346", "eng4", "fl12", "north", "room_ccc", "z1", "sensor1", "monitor", "PIR"],
    ["347", "eng4", "fl12", "north", "room_ccc", "z1", "sensor1", "monitor", "beeper"],
    ["348", "eng4", "fl12", "north", "room_ccc", "z1", "sensor1", "monitor", "humidity"],
    ["349", "eng4", "fl12", "north", "room_ccc", "z1", "sensor1", "monitor", "illuminance"],
    ["350", "eng4", "fl12", "north", "room_ccc", "z1", "sensor1", "monitor", "temperature"],
    ["351", "eng4", "fl12", "north", "room_hbm", "z1", "aircon1", "monitor", "energy"],
    ["352", "eng4", "fl12", "north", "room_hbm", "z1", "outlet1", "monitor", "energy"],
    ["353", "eng4", "fl12", "north", "room_kar", "z1", "aircon1", "monitor", "energy"],
    ["354", "eng4", "fl12", "north", "room_kar", "z1", "sensor1", "monitor", "PIR"],
    ["355", "eng4", "fl12", "north", "room_kar", "z1", "sensor1", "monitor", "humidity"],
    ["356", "eng4", "fl12", "north", "room_kar", "z1", "sensor1", "monitor", "illuminance"],
    ["357", "eng4", "fl12", "north", "room_kar", "z1", "sensor1", "monitor", "temperature"],
    ["358", "eng4", "fl12", "north", "room_nhc", "z1", "aircon1", "monitor", "energy"],
    ["359", "eng4", "fl12", "north", "room_nhc", "z1", "outlet1", "monitor", "energy"],
    ["360", "eng4", "fl12", "north", "room_nhc", "z1", "sensor1", "monitor", "PIR"],
    ["361", "eng4", "fl12", "north", "room_nhc", "z1", "sensor1", "monitor", "beeper"],
    ["362", "eng4", "fl12", "north", "room_nhc", "z1", "sensor1", "monitor", "humidity"],
    ["363", "eng4", "fl12", "north", "room_nhc", "z1", "sensor1", "monitor", "illuminance"],
    ["364", "eng4", "fl12", "north", "room_nhc", "z1", "sensor1", "monitor", "temperature"],
    ["365", "eng4", "fl12", "north", "room_scn", "z1", "aircon1", "monitor", "energy"],
    ["366", "eng4", "fl12", "north", "room_scn", "z1", "outlet1", "monitor", "energy"],
    ["367", "eng4", "fl12", "north", "room_scn", "z1", "sensor1", "monitor", "PIR"],
    ["368", "eng4", "fl12", "north", "room_scn", "z1", "sensor1", "monitor", "humidity"],
    ["369", "eng4", "fl12", "north", "room_scn", "z1", "sensor1", "monitor", "illuminance"],
    ["370", "eng4", "fl12", "north", "room_scn", "z1", "sensor1", "monitor", "temperature"],
    ["371", "eng4", "fl12", "north", "room_spw", "z1", "aircon1", "monitor", "energy"],
    ["372", "eng4", "fl12", "north", "room_spw", "z1", "sensor1", "monitor", "PIR"],
    ["373", "eng4", "fl12", "north", "room_spw", "z1", "sensor1", "monitor", "humidity"],
    ["374", "eng4", "fl12", "north", "room_spw", "z1", "sensor1", "monitor", "illuminance"],
    ["375", "eng4", "fl12", "north", "room_spw", "z1", "sensor1", "monitor", "temperature"],
    ["376", "eng4", "fl12", "north", "room_ttn", "z1", "aircon1", "monitor", "energy"],
    ["377", "eng4", "fl12", "north", "room_ttn", "z1", "outlet1", "monitor", "energy"],
    ["378", "eng4", "fl12", "north", "room_ttn", "z1", "sensor1", "monitor", "PIR"],
    ["379", "eng4", "fl12", "north", "room_ttn", "z1", "sensor1", "monitor", "beeper"],
    ["380", "eng4", "fl12", "north", "room_ttn", "z1", "sensor1", "monitor", "humidity"],
    ["381", "eng4", "fl12", "north", "room_ttn", "z1", "sensor1", "monitor", "illuminance"],
    ["382", "eng4", "fl12", "north", "room_ttn", "z1", "sensor1", "monitor", "temperature"],
    ["383", "eng4", "fl12", "north", "studentroom_psrl", "z1", "aircon1", "monitor", "energy"],
    ["384", "eng4", "fl12", "north", "studentroom_psrl", "z1", "light1", "monitor", "energy"],
    ["385", "eng4", "fl12", "north", "studentroom_psrl", "z1", "outlet1", "monitor", "energy"],
    ["386", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor1", "monitor", "humidity"],
    ["387", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor1", "monitor", "illuminance"],
    ["388", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor1", "monitor", "pir"],
    ["389", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor1", "monitor", "temperature"],
    ["390", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor2", "monitor", "humidity"],
    ["391", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor2", "monitor", "illuminance"],
    ["392", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor2", "monitor", "pir"],
    ["393", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor2", "monitor", "temperature"],
    ["394", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor3", "monitor", "humidity"],
    ["395", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor3", "monitor", "illuminance"],
    ["396", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor3", "monitor", "pir"],
    ["397", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor3", "monitor", "temperature"],
    ["398", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor4", "monitor", "humidity"],
    ["399", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor4", "monitor", "illuminance"],
    ["400", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor4", "monitor", "pir"],
    ["401", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor4", "monitor", "temperature"],
    ["402", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor5", "monitor", "humidity"],
    ["403", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor5", "monitor", "illuminance"],
    ["404", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor5", "monitor", "pir"],
    ["405", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor5", "monitor", "temperature"],
    ["406", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor6", "monitor", "humidity"],
    ["407", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor6", "monitor", "illuminance"],
    ["408", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor6", "monitor", "pir"],
    ["409", "eng4", "fl12", "north", "studentroom_psrl", "z1", "sensor6", "monitor", "temperature"],
    ["410", "eng4", "fl12", "north", "studentroom_psrl", "z2", "aircon1", "monitor", "energy"],
    ["411", "eng4", "fl12", "north", "studentroom_psrl", "z2", "light1", "monitor", "energy"],
    ["412", "eng4", "fl12", "north", "studentroom_psrl", "z2", "light2", "monitor", "energy"],
    ["413", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor2", "monitor", "humidity"],
    ["414", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor2", "monitor", "illuminance"],
    ["415", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor2", "monitor", "pir"],
    ["416", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor2", "monitor", "temperature"],
    ["417", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor3", "monitor", "humidity"],
    ["418", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor3", "monitor", "illuminance"],
    ["419", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor3", "monitor", "pir"],
    ["420", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor3", "monitor", "temperature"],
    ["421", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor4", "monitor", "humidity"],
    ["422", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor4", "monitor", "illuminance"],
    ["423", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor4", "monitor", "pir"],
    ["424", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor4", "monitor", "temperature"],
    ["425", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor5", "monitor", "humidity"],
    ["426", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor5", "monitor", "illuminance"],
    ["427", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor5", "monitor", "pir"],
    ["428", "eng4", "fl12", "north", "studentroom_psrl", "z2", "sensor5", "monitor", "temperature"],
    ["429", "eng4", "fl12", "north", "studentroom_psrl", "z3", "aircon_3ph1", "monitor", "energy_r"],
    ["430", "eng4", "fl12", "north", "studentroom_psrl", "z3", "aircon_3ph1", "monitor", "energy_s"],
    ["431", "eng4", "fl12", "north", "studentroom_psrl", "z3", "aircon_3ph1", "monitor", "energy_t"],
    ["432", "eng4", "fl12", "north", "studentroom_psrl", "z3", "light1", "monitor", "energy"],
    ["433", "eng4", "fl12", "north", "studentroom_psrl", "z3", "light2", "monitor", "energy"],
    ["434", "eng4", "fl12", "north", "studentroom_psrl", "z3", "outlet1", "monitor", "energy"],
    ["435", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor1", "monitor", "humidity"],
    ["436", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor1", "monitor", "illuminance"],
    ["437", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor1", "monitor", "pir"],
    ["438", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor1", "monitor", "temperature"],
    ["439", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor2", "monitor", "humidity"],
    ["440", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor2", "monitor", "illuminance"],
    ["441", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor2", "monitor", "pir"],
    ["442", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor2", "monitor", "temperature"],
    ["443", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor3", "monitor", "humidity"],
    ["444", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor3", "monitor", "illuminance"],
    ["445", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor3", "monitor", "pir"],
    ["446", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor3", "monitor", "temperature"],
    ["447", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor4", "monitor", "humidity"],
    ["448", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor4", "monitor", "illuminance"],
    ["449", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor4", "monitor", "pir"],
    ["450", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor4", "monitor", "temperature"],
    ["451", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor5", "monitor", "humidity"],
    ["452", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor5", "monitor", "illuminance"],
    ["453", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor5", "monitor", "pir"],
    ["454", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor5", "monitor", "temperature"],
    ["455", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor6", "monitor", "humidity"],
    ["456", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor6", "monitor", "illuminance"],
    ["457", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor6", "monitor", "pir"],
    ["458", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor6", "monitor", "temperature"],
    ["459", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor7", "monitor", "humidity"],
    ["460", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor7", "monitor", "illuminance"],
    ["461", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor7", "monitor", "pir"],
    ["462", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor7", "monitor", "temperature"],
    ["463", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor8", "monitor", "humidity"],
    ["464", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor8", "monitor", "illuminance"],
    ["465", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor8", "monitor", "pir"],
    ["466", "eng4", "fl12", "north", "studentroom_psrl", "z3", "sensor8", "monitor", "temperature"],
    ["467", "eng4", "fl12", "north", "studentroom_psrl", "z4", "aircon_3ph1", "monitor", "energy_r"],
    ["468", "eng4", "fl12", "north", "studentroom_psrl", "z4", "aircon_3ph1", "monitor", "energy_s"],
    ["469", "eng4", "fl12", "north", "studentroom_psrl", "z4", "aircon_3ph1", "monitor", "energy_t"],
    ["470", "eng4", "fl12", "north", "studentroom_psrl", "z4", "light1", "monitor", "energy"],
    ["471", "eng4", "fl12", "north", "studentroom_psrl", "z4", "light2", "monitor", "energy"],
    ["472", "eng4", "fl12", "north", "studentroom_psrl", "z4", "outlet1", "monitor", "energy"],
    ["473", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor1", "monitor", "humidity"],
    ["474", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor1", "monitor", "illuminance"],
    ["475", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor1", "monitor", "pir"],
    ["476", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor1", "monitor", "temperature"],
    ["477", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor2", "monitor", "humidity"],
    ["478", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor2", "monitor", "illuminance"],
    ["479", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor2", "monitor", "pir"],
    ["480", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor2", "monitor", "temperature"],
    ["481", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor3", "monitor", "humidity"],
    ["482", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor3", "monitor", "illuminance"],
    ["483", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor3", "monitor", "pir"],
    ["484", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor3", "monitor", "temperature"],
    ["485", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor4", "monitor", "humidity"],
    ["486", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor4", "monitor", "illuminance"],
    ["487", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor4", "monitor", "pir"],
    ["488", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor4", "monitor", "temperature"],
    ["489", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor5", "monitor", "humidity"],
    ["490", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor5", "monitor", "illuminance"],
    ["491", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor5", "monitor", "pir"],
    ["492", "eng4", "fl12", "north", "studentroom_psrl", "z4", "sensor5", "monitor", "temperature"],
    ["493", "eng4", "fl12", "south", "lab_csbl", "z1", "aircon1", "monitor", "energy"],
    ["494", "eng4", "fl12", "south", "lab_csbl", "z1", "light1", "monitor", "energy"],
    ["495", "eng4", "fl12", "south", "lab_csbl", "z1", "outlet1", "monitor", "energy"],
    ["496", "eng4", "fl12", "south", "lab_csbl", "z1", "outlet2", "monitor", "energy"],
    ["497", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor1", "monitor", "humidity"],
    ["498", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor1", "monitor", "illuminance"],
    ["499", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor1", "monitor", "pir"],
    ["500", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor1", "monitor", "temperature"],
    ["501", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor2", "monitor", "humidity"],
    ["502", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor2", "monitor", "illuminance"],
    ["503", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor2", "monitor", "pir"],
    ["504", "eng4", "fl12", "south", "lab_csbl", "z1", "sensor2", "monitor", "temperature"],
    ["505", "eng4", "fl12", "south", "lab_csbl", "z2", "aircon1", "monitor", "energy"],
    ["506", "eng4", "fl12", "south", "lab_csbl", "z2", "outlet1", "monitor", "energy"],
    ["507", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor1", "monitor", "humidity"],
    ["508", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor1", "monitor", "illuminance"],
    ["509", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor1", "monitor", "pir"],
    ["510", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor1", "monitor", "temperature"],
    ["511", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor2", "monitor", "humidity"],
    ["512", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor2", "monitor", "illuminance"],
    ["513", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor2", "monitor", "pir"],
    ["514", "eng4", "fl12", "south", "lab_csbl", "z2", "sensor2", "monitor", "temperature"],
    ["515", "eng4", "fl12", "south", "lab_studio", "z1", "aircon1", "monitor", "energy"],
    ["516", "eng4", "fl12", "south", "lab_studio", "z1", "light1", "monitor", "energy"],
    ["517", "eng4", "fl12", "south", "lab_studio", "z1", "sensor1", "monitor", "humidity"],
    ["518", "eng4", "fl12", "south", "lab_studio", "z1", "sensor1", "monitor", "illuminance"],
    ["519", "eng4", "fl12", "south", "lab_studio", "z1", "sensor1", "monitor", "pir"],
    ["520", "eng4", "fl12", "south", "lab_studio", "z1", "sensor1", "monitor", "temperature"],
    ["521", "eng4", "fl12", "south", "meetingroom_commu", "z1", "aircon1", "monitor", "energy"],
    ["522", "eng4", "fl12", "south", "meetingroom_commu", "z1", "light1", "monitor", "energy"],
    ["523", "eng4", "fl12", "south", "meetingroom_commu", "z1", "outlet1", "monitor", "energy"],
    ["524", "eng4", "fl12", "south", "meetingroom_commu", "z1", "outlet2", "monitor", "energy"],
    ["525", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor1", "monitor", "humidity"],
    ["526", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor1", "monitor", "illuminance"],
    ["527", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor1", "monitor", "pir"],
    ["528", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor1", "monitor", "temperature"],
    ["529", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor2", "monitor", "humidity"],
    ["530", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor2", "monitor", "illuminance"],
    ["531", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor2", "monitor", "pir"],
    ["532", "eng4", "fl12", "south", "meetingroom_commu", "z1", "sensor2", "monitor", "temperature"],
    ["533", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "aircon1", "monitor", "energy"],
    ["534", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "light1", "monitor", "energy"],
    ["535", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "outlet1", "monitor", "energy"],
    ["536", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor1", "monitor", "humidity"],
    ["537", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor1", "monitor", "illuminance"],
    ["538", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor1", "monitor", "pir"],
    ["539", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor1", "monitor", "temperature"],
    ["540", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor2", "monitor", "humidity"],
    ["541", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor2", "monitor", "illuminance"],
    ["542", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor2", "monitor", "pir"],
    ["543", "eng4", "fl12", "south", "meetingroom_sjp", "z1", "sensor2", "monitor", "temperature"],
    ["544", "eng4", "fl12", "south", "officeroom_commu", "z1", "aircon1", "monitor", "energy"],
    ["545", "eng4", "fl12", "south", "officeroom_commu", "z1", "light1", "monitor", "energy"],
    ["546", "eng4", "fl12", "south", "officeroom_commu", "z1", "light2", "monitor", "energy"],
    ["547", "eng4", "fl12", "south", "officeroom_commu", "z1", "outlet1", "monitor", "energy"],
    ["548", "eng4", "fl12", "south", "officeroom_commu", "z1", "sensor1", "monitor", "humidity"],
    ["549", "eng4", "fl12", "south", "officeroom_commu", "z1", "sensor1", "monitor", "illuminance"],
    ["550", "eng4", "fl12", "south", "officeroom_commu", "z1", "sensor1", "monitor", "pir"],
    ["551", "eng4", "fl12", "south", "officeroom_commu", "z1", "sensor1", "monitor", "temperature"],
    ["552", "eng4", "fl12", "south", "officeroom_commu", "z2", "aircon1", "monitor", "energy"],
    ["553", "eng4", "fl12", "south", "officeroom_commu", "z2", "light1", "monitor", "energy"],
    ["554", "eng4", "fl12", "south", "officeroom_commu", "z2", "outlet1", "monitor", "energy"],
    ["555", "eng4", "fl12", "south", "officeroom_commu", "z2", "sensor1", "monitor", "humidity"],
    ["556", "eng4", "fl12", "south", "officeroom_commu", "z2", "sensor1", "monitor", "illuminance"],
    ["557", "eng4", "fl12", "south", "officeroom_commu", "z2", "sensor1", "monitor", "pir"],
    ["558", "eng4", "fl12", "south", "officeroom_commu", "z2", "sensor1", "monitor", "temperature"],
    ["559", "eng4", "fl12", "south", "room_ptp", "z1", "aircon1", "monitor", "energy"],
    ["560", "eng4", "fl12", "south", "room_ptp", "z1", "outlet1", "monitor", "energy"],
    ["561", "eng4", "fl12", "south", "room_ptp", "z1", "sensor1", "monitor", "humidity"],
    ["562", "eng4", "fl12", "south", "room_ptp", "z1", "sensor1", "monitor", "illuminance"],
    ["563", "eng4", "fl12", "south", "room_ptp", "z1", "sensor1", "monitor", "pir"],
    ["564", "eng4", "fl12", "south", "room_ptp", "z1", "sensor1", "monitor", "temperature"],
    ["565", "eng4", "fl12", "south", "room_snp", "z1", "aircon1", "monitor", "energy"],
    ["566", "eng4", "fl12", "south", "room_snp", "z1", "light1", "monitor", "energy"],
    ["567", "eng4", "fl12", "south", "room_tak", "z1", "aircon1", "monitor", "energy"],
    ["568", "eng4", "fl12", "south", "room_tak", "z1", "light1", "monitor", "energy"],
    ["569", "eng4", "fl12", "south", "room_tak", "z1", "outlet1", "monitor", "energy"],
    ["570", "eng4", "fl12", "south", "room_tak", "z1", "sensor1", "monitor", "humidity"],
    ["571", "eng4", "fl12", "south", "room_tak", "z1", "sensor1", "monitor", "illuminance"],
    ["572", "eng4", "fl12", "south", "room_tak", "z1", "sensor1", "monitor", "pir"],
    ["573", "eng4", "fl12", "south", "room_tak", "z1", "sensor1", "monitor", "temperature"],
    ["574", "eng4", "fl12", "south", "room_teerapong", "z1", "aircon1", "monitor", "energy"],
    ["575", "eng4", "fl12", "south", "room_teerapong", "z1", "sensor1", "monitor", "humidity"],
    ["576", "eng4", "fl12", "south", "room_teerapong", "z1", "sensor1", "monitor", "illuminance"],
    ["577", "eng4", "fl12", "south", "room_teerapong", "z1", "sensor1", "monitor", "pir"],
    ["578", "eng4", "fl12", "south", "room_teerapong", "z1", "sensor1", "monitor", "temperature"],
    ["579", "eng4", "fl12", "south", "room_wbk", "z1", "aircon1", "monitor", "energy"],
    ["580", "eng4", "fl12", "south", "room_wbk", "z1", "light1", "monitor", "energy"],
    ["581", "eng4", "fl12", "south", "room_wbk", "z1", "sensor1", "monitor", "humidity"],
    ["582", "eng4", "fl12", "south", "room_wbk", "z1", "sensor1", "monitor", "illuminance"],
    ["583", "eng4", "fl12", "south", "room_wbk", "z1", "sensor1", "monitor", "pir"],
    ["584", "eng4", "fl12", "south", "room_wbk", "z1", "sensor1", "monitor", "temperature"]
]
let zonepirlist = []
let energylist = []
let zoneenergy = {}

for (const each of listfile) {
    if (each[each.length - 1] == "pir") {
        const zone = each[1]+"-"+each[2]+"-"+each[3]+"-"+each[4]+"-"+each[5];
        zonepirlist.push(zone)
        zoneenergy[zone] = {
            pir: each[0],
            energy: []
        }
    }
}

for (const each of listfile) {
    if (each[each.length - 1] == "energy") {
        const zone = each[1]+"-"+each[2]+"-"+each[3]+"-"+each[4]+"-"+each[5];
        if (zonepirlist.includes(zone)) {
            energylist.push(each)
            if (each[each.length - 1] == "energy" && each[6].indexOf("aircon") != -1)
                zoneenergy[zone]["energy"].push(each[0])
        }
    }
}

let jobs = []

for (const eachzone in zoneenergy) {
    for (const pointid of zoneenergy[eachzone]["energy"]) {
        const job = {
            pirpointid: zoneenergy[eachzone]["pir"],
            energypointid: pointid
        }
        jobs.push(job)
    }
}

const Wreck = require('@hapi/wreck');

let path = 'http://newwebserver.parallelcomputingdemo.161.200.90.106.xip.io';
// let path = 'http://localhost:8080'

let main = async () => {

    let laps = []
    const parallel = 25
    const maxlap = 4
    console.log(jobs.length);
    while (jobs.length > 0) laps.push(jobs.splice(0, parallel))
    laps = laps.splice(0, maxlap)

    let result = []

    const executejob = (pir, energy) => {
        return Wreck
            .get(path + `/csv/${pir}.csv/${energy}.csv`, { json: true })
            .then((res) => res.payload)
            .then((res) => {
                return {
                    "allenergy": parseFloat(res.allenergy),
                    "wastedenergy": parseFloat(res.wastedenergy),
                    "usefulenergy": parseFloat(res.usefulenergy)
                }
            })
            .catch((e) => console.log("Error: " + e.message))
    }

    n = 0

    while (laps.length > 0) {
        n++
        lap = laps.shift()
        lapresult = await Promise.all(lap.map((job) => executejob(job.pirpointid, job.energypointid)))
        result = result.concat(lapresult);
        console.log(n);
        console.log(lapresult);
    }

    let summarize = {
        allenergy: 0,
        wastedenergy: 0,
        usefulenergy: 0
    }


    result.map((res) => {
        summarize.allenergy += res.allenergy
        summarize.wastedenergy += res.wastedenergy
        summarize.usefulenergy += res.usefulenergy
    })

    console.log(summarize);
}

main();